name: Release Charts

on:
  push:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Create index file
        uses: yeouchien/helm3-action@f3a7c239c5c60777210c8e631839edf5dd3fa29c
        with:
          command: repo index --url https://pavelmikhailouski.github.io/charts ./gh-pages/charts
